### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by liuyatao** [didilinkin/Shangchao-admin-element-ui#2]
➜  Shangchao-admin-element-ui git:(master) npm run dev

> shangchao-admin-element-ui@1.0.0 dev /Users/liuyatao/Project/Shangchao-admin-element-ui
> node build/dev-server.js

module.js:487
    throw err;
    ^

Error: Cannot find module '../dist/static/api/viewAPI.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liuyatao/Project/Shangchao-admin-element-ui/build/dev-server.js:27:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shangchao-admin-element-ui@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shangchao-admin-element-ui@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuyatao/.npm/_logs/2017-06-10T02_12_38_438Z-debug.log

**Comment by fuminjie** [comment]
Modify file dev-server.js27 line,'../dist/static/api/viewAPI.json' to '../static/api/viewAPI.json'。

**Comment by didilinkin** [comment]
@liuyatao 您好, 您能说一下你的运行环境吗？

**Comment by didilinkin** [comment]
@liuyatao  
我本地的开发环境
Nodejs版本： v7.9.0
npm版本: v5.0.3
webpack全局版本: 1.13.3

我知道问题在哪里了： 您需要先 `yarn run build`打包一下( 将`viewAPI.json`这个静态文件输出到`dist`文件夹 )

build打包完毕之后,  再运行 yarn run dev 。 应该就没问题了

是我的问题.  我会改正 `README.md`  

谢谢 👍

**Comment by didilinkin** [comment]
@fuminjie  请先用 `yarn run build` 打包一下,  然后再 使用 `yarn run dev` 测试

也可以使用`npm` 替换 `yarn` ； 同样效果

**Comment by didilinkin** [comment]
没啥疑问的话 我要关闭啦？

**Comment by fuminjie** [comment]
@didilinkin 我们项目由webpack1升级webpack2参考了你们的配置，tks。你们有涉及到同时打开多路由的方案没，有没有好的建议。
![image](https://user-images.githubusercontent.com/22384333/27329768-712c0332-55e9-11e7-95f0-f1beeaad1c72.png)

**Comment by didilinkin** [comment]
@fuminjie  非常高兴 我的webpack配置 能够为你们提供帮助， 在这里也向你们推荐 我的另一个项目[Shangchao-pms-wx](https://github.com/didilinkin/Shangchao-pms-wx)配置 ， 它的配置里面还带了 Fakerjs 和 Mockjs 模拟接口数据的服务( 如果你们需要的话 )；

你说的同时打开多路由的方案？  听起来很酷  但是我没太明白它的应用场景， 能说明一下吗？

**Comment by fuminjie** [comment]
hi:
            谢谢你们提供的帮助,我们的业务每个菜单关联性很强，所以需要打开多菜单并有菜单权限控制。目前用tab 组件的方式实现，但是放弃了嵌套路由。不知道有好的建议没。





329753704@qq.com
 
发件人： 晓迪
发送时间： 2017-06-21 10:08
收件人： didilinkin/Shangchao-admin-element-ui
抄送： fuminjie; Mention
主题： Re: [didilinkin/Shangchao-admin-element-ui] 运行报错 (#2)
@fuminjie 非常高兴 我的webpack配置 能够为你们提供帮助， 在这里也向你们推荐 我的另一个项目Shangchao-pms-wx配置 ， 它的配置里面还带了 Fakerjs 和 Mockjs 模拟接口数据的服务( 如果你们需要的话 )；
你说的同时打开多路由的方案？ 听起来很酷 但是我没太明白它的应用场景， 能说明一下吗？

**Comment by didilinkin** [comment]
@fuminjie 我似乎明白了你的想法： 因为你们的一些菜单选项下, 还有很多的业务逻辑 所以需要使用tab来在内容模版那里进行切换， 而你认为tab切换的方法 就无法使用路由来进行更深的嵌套路由方法。 不知道是不是应该这样理解？  A版块下的a模块( URL: /A/a ) 它的内容页里面还要分 3个tab( Tab: x 、y 、 z ) . 你们认为不能使用嵌套路由的方法( URL: /A/a/x ) 这种思路 。  不知道猜测的是否正确？

首先 你们的这种思路我认为是正确的,  在a版块下的tab 切换也是不错的方法， 但是不需要再使用路由进行更深的嵌套路由控制了。  只需要使用 v-show选项 进行显示隐藏即可( 动态显示 或者 隐藏 x 、y 或者 z )；

如果还涉及到权限的显示, 比如userA的权限只能显示 x和y，  则需要先使用 v-if 来控制tab的显示( v-if是惰性的 ) ， 然后里面用v-show来控制tab的切换

最后可以考虑使用vuex进行 管理它们之间的状态共享，  这样应该可以解决你们的需求

如果还有疑问还可以继续向我提问

**Comment by fuminjie** [comment]
谢谢你们给的建议,我们采用的方式是在vuex中维护用户打开的菜单。我们一直在寻找是否有更优雅的方式实现多菜单同时打开的功能。


329753704@qq.com
 
发件人： 晓迪
发送时间： 2017-06-21 22:29
收件人： didilinkin/Shangchao-admin-element-ui
抄送： fuminjie; Mention
主题： Re: [didilinkin/Shangchao-admin-element-ui] 运行报错 (#2)
@fuminjie 我似乎明白了你的想法： 因为你们的一些菜单选项下, 还有很多的业务逻辑 所以需要使用tab来在内容模版那里进行切换， 而你认为tab切换的方法 就无法使用路由来进行更深的嵌套路由方法。 不知道是不是应该这样理解？ A版块下的a模块( URL: /A/a ) 它的内容页里面还要分 3个tab( Tab: x 、y 、 z ) . 你们认为不能使用嵌套路由的方法( URL: /A/a/x ) 这种思路 。 不知道猜测的是否正确？
首先 你们的这种思路我认为是正确的, 在a版块下的tab 切换也是不错的方法， 但是不需要再使用路由进行更深的嵌套路由控制了。 只需要使用 v-show选项 进行显示隐藏即可( 动态显示 或者 隐藏 x 、y 或者 z )；
如果还涉及到权限的显示, 比如userA的权限只能显示 x和y， 则需要先使用 v-if 来控制tab的显示( v-if是惰性的 ) ， 然后里面用v-show来控制tab的切换
最后可以考虑使用vuex进行 管理它们之间的状态共享， 这样应该可以解决你们的需求
如果还有疑问还可以继续向我提问
