### ISSUE TITLE
沒有Demo演示之類的嗎？

### ISSUE THREAD

**Issue by carry0987** [didilinkin/Shangchao-admin-element-ui#3]
希望有能夠參考的頁面

**Comment by carry0987** [comment]
非常感謝！！

**Comment by didilinkin** [comment]
@carry0987  你好， 静态演示页面 已经部署完毕， 可点击http://yanxiaodi.coding.me/Element-admin/#/ 进行查看

**Comment by carry0987** [comment]
我的媽啊，這個演示也太吊了吧

2017-07-09 14:45 GMT+08:00 晓迪 <notifications@github.com>:

**Comment by didilinkin** [comment]
# 啊？ 是有什么疑问吗  还是 没有需要的内容？@carry0987

**Comment by carry0987** [comment]
不不不，只是發現這個演示做得太好了..

**Comment by didilinkin** [comment]
@carry0987 😄哈哈， 我觉得还有很多地方可以改进一下。  没想到这么多人会点赞这个项目。  我会认真再好好重构一下的。  如果有什么好的建议  可以告诉我( 别太麻烦的功能需求就行， 最近忙着写React呢 )

**Comment by didilinkin** [comment]
#
